更新发布工作流以支持 Maven 发布过程。优化项目部署效率。

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,40 +33,22 @@ jobs:
           settings-path: ${{ github.workspace }} # location for the settings.xml file
 
       - name: Get project version from pom.xml
+        if: github.event_name == 'push'
         id: get_version
         run: |
           echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
 
-      - name: Print project version
-        run: echo "The project version is ${{ env.VERSION }}"
-
-      - name: Check if Release exists
-        id: check-release
+      - name: Handle existing Release
+        if: github.event_name == 'push'
         run: |
-          # Check if the release exists
-          RESPONSE=$(gh release view v${{ env.VERSION }} -R ${{ github.repository }} 2>&1 || true)
-          if echo "$RESPONSE" | grep -q "Not Found"; then
-            echo "Release v${{ env.VERSION }} does not exist. Skipping deletion."
-            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
+          RELEASE_EXISTS=$(gh release view v${{ env.VERSION }} -R ${{ github.repository }} 2>&1 || true)
+          if echo "$RELEASE_EXISTS" | grep -q "Not Found"; then
+            echo "Release v${{ env.VERSION }} does not exist. Proceeding to create."
           else
-            echo "Release v${{ env.VERSION }} exists."
-            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
+            echo "Release v${{ env.VERSION }} exists. Deleting existing release."
+            gh release delete v${{ env.VERSION }} -R ${{ github.repository }} -y --cleanup-tag || echo "Failed to delete release. It might not exist or there might be another issue."
           fi
-
-      - name: Delete Release if exists
-        if: env.RELEASE_EXISTS == 'true'
-        run: |
-          # Try to delete the release and handle errors gracefully
-          set +e
-          gh release delete v${{ env.VERSION }} -R ${{ github.repository }} -y --cleanup-tag
-          if [ $? -eq 0 ]; then
-            echo "Release v${{ env.VERSION }} deleted successfully."
-          else
-            echo "Failed to delete release v${{ env.VERSION }}. It might not exist or there might be another issue."
-          fi
-
-      - name: Create Release with temp note
-        run: gh release create v${{ env.VERSION }} --generate-notes
+          gh release create v${{ env.VERSION }} --generate-notes
 
       - name: Build with Maven
         run: mvn -B package --file pom.xml
@@ -76,4 +58,5 @@ jobs:
         run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
 
       - name: Upload to GitHub Release
+        if: github.event_name == 'push'
         run: gh release upload v${{ env.VERSION }} target/queqiao-tool-${{ env.VERSION }}.jar --clobber
